

# alacritty.toml

import = [
        "~/.config/alacritty/themes/nordic.toml"
]

[window]
blur = true
opacity = 0.8
padding = { x = 0, y = 0 }
dimensions = { columns = 120, lines = 25 }

[font]
size = 13
bold = { family = "Sarasa Term J" }
normal = { family = "Sarasa Term J" }
italic = { family = "Sarasa Term J" }
bold_italic = { family = "Sarasa Term J" }

[cursor]
style = { shape = "Beam" }

[mouse]
hide_when_typing = true
