preload = /home/km/pictures/localFile/unsplash.com/victor-dittiere-5WYUKwkM7EU-unsplash.jpg
wallpaper = eDP-1,/home/km/pictures/localFile/unsplash.com/victor-dittiere-5WYUKwkM7EU-unsplash.jpg
splash = false

#fully disable ipc
# ipc = off

