preload = /home/km/pictures/localFiles/unsplash.com/chandler-cruttenden-w8hWTFpGtpY-unsplash.jpg
wallpaper = eDP-1,/home/km/pictures/localFiles/unsplash.com/chandler-cruttenden-w8hWTFpGtpY-unsplash.jpg
splash = false

#fully disable ipc
# ipc = off

