#!/bin/sh
#
#
#  ／l、             
#（ﾟ､ ｡ ７         
#  l  ~ヽ       
#  じしf_,)ノ
#
#
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap

# unset XDG_CURRENT_DESKTOP
# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

xrdb -merge ~./Xresources

# start some nice programs

if [ -n "`/etc/X11/chooser.sh`" ]; then
 command="`/etc/X11/chooser.sh`"
else
 failsafe="yes"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?* ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
if [ -n "$failsafe" ]; then
	#xrandr --setprovideroutputsource modesetting NVIDIA-0
	#xrandr --auto
        eval "$(dbus-launch --sh-syntax --exit-with-session)"
	feh --bg-fill ~/.wp &
        dwmblocks &
	fcitx5 -d
        xfce4-power-manager --daemon &
        sudo AdGuardHome -s start &
        picom --experimental-backends -b &
else
	exec $command
fi
