

# hypr/hyprpaper.conf

preload = /home/km/pictures/localFiles/unsplash.com/alexander-grey-62vi3TG5EDg-unsplash.jpg
wallpaper = eDP-1,/home/km/pictures/localFiles/unsplash.com/alexander-grey-62vi3TG5EDg-unsplash.jpg
splash = false

#fully disable ipc
# ipc = off
