

# xorgServer/xorg.conf

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0"
    Option	   "AllowNVIDIAGPUScreens" "true"
    Option	   "AllowPRIMEDisplayOffloadSink" "true"
EndSection

Section "Files"
EndSection

Section "InputClass"
    Identifier     "libinput pointer catchall"
    Driver         "libinput"
    MatchIsPointer "On"
    MatchDevicePath "/dev/input/event*"
    Option         "AccelProfile" "flat"
    Option         "AccelSpeed" "0"
    Option	   "ScrollMethod" "twofinger"
    Option         "HorizontalScrolling" "true"
    Option         "NaturalScrolling" "true"
EndSection

Section "InputClass"
    Identifier     "libinput keyboard catchall"
    Driver         "libinput"
    Option	   "XkbLayout" "jp"
    Option	   "XkbOptions" "ctrl:swapcaps"
    MatchIsKeyboard "On"
    MatchDevicePath "/dev/input/event*"
EndSection

Section "InputClass"
    Identifier     "libinput touchpad catchall"
    Driver         "libinput"
    MatchIsTouchpad "On"
    MatchDevicePath "/dev/input/event*"
    Option         "Tapping" "true"
    Option         "TappingDrag" "true"
    Option	   "ScrollMethod" "twofinger"
    Option         "HorizontalScrolling" "true"
    Option         "NaturalScrolling" "true"
EndSection

Section "Module"
    Load	   "fb"
    Load	   "shadow"
    Load	   "exa"
    Load	   "glamorel"
    Load	   "glx"
    Load	   "dri3"
EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "Unknown"
    Option         "DPMS"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BusID          "PCI:1:0:0"
    Option         "Accel" "true"
    Option         "RenderAccel" "true"
    Option         "NoFlip" "false"
    Option         "SWCursor" "false"
    Option         "HWCursor" "true"
    Option         "DamageEvents" "true"
    Option         "ModeDebug" "false"
    Option         "AllowSHMPixmaps" "false"
    Option         "SidebandSocketPath" "/tmp"
    Option         "UseSysmemPixmapAccel" "true"
    Option         "MultiSampleCompatibility" "true"
    Option         "AllowEmptyInitialConfiguration" "true"
    Option         "ForceCompositionPipline" "true"
    Option         "AllowIndirectGLXProtocol" "false"
    Option         "TripleBuffer" "true"
    Option         "Stereo" "0"
    Option         "BaseMosaic" "false"
    Option         "MultiGPU" "false"
    Option         "SLI" "false"
    Option         "PrimaryGPU" "yes"
EndSection

Section "Device"
    Identifier     "Device1"
    Driver         "modesetting"
    VendorName     "Intel"
    BusID          "PCI:0:2:0"
    Option         "AccelMethod" "glamor"
    Option         "DRI" "3"
    Option         "TearFree" "true"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "AllowEmptyInitialConfiguration" "True"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection


Section "ServerFlags"
	Option     "DontVTSwitch" "true"
	Option     "DontZap" "true"
EndSection
