conky.config = {
--==============================================================================

--  Created : 2024/Mar/16
--  This theme is for conky version 1.10.8 or newer
-- 
--  DNOCES
--  ( A part of Ursa Major Conky themes pack )
--
--  author  : Closebox73
--  version : 1.0
--  variant : Celcius
--  license : Distributed under the terms of GPLv3
--  notes   : Created on 1366x768 Monitor

--==============================================================================

-- Size and Position settings --
  alignment = 'bottom_left',
  gap_x = 20,
  gap_y = 70,
  minimum_height = 400,
  minimum_width = 400,
  
-- Text settings --
  use_xft = true,
  override_utf8_locale = true,
  font = 'Roboto:size=1',
  
-- Color Settings --
  default_color = '#FFFFFF',
  default_outline_color = 'white',
  default_shade_color = 'white',
  color1 = 'FF1493',
  
-- Window Settings --
  background = false,
  border_width = 1,
  draw_borders = false,
  draw_graph_borders = true,
  draw_outline = false,
  draw_shades = false,
  own_window = true,
  own_window_colour = '000000',
  own_window_class = 'Conky',
  draw_blended = false,
  own_window_argb_visual = false,
  own_window_type = 'override',

  own_window_transparent = true,
  own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
  stippled_borders = 0,
  
-- Others --
  cpu_avg_samples = 2,
  net_avg_samples = 2,
  double_buffer = true,
  out_to_console = false,
  out_to_stderr = false,
  extra_newline = false,
  update_interval = 1,
  uppercase = true,
  use_spacer = 'none',
  show_graph_scale = true,
  show_graph_range = true,
}

conky.text = [[
${execi 300 ~/.config/conky/Dnoces/scripts/weather-v2.0.sh}\
${image ~/.config/conky/Dnoces/res/bg.png -s 6x55 -p 0,0}\
${image ~/.config/conky/Dnoces/res/bg1.png -s 6x55 -p 0,55}\
${image ~/.config/conky/Dnoces/res/bg2.png -s 6x55 -p 0,110}\
${image ~/.config/conky/Dnoces/res/bg3.png -s 6x55 -p 0,165}\
${offset 20}${voffset 3}${color}${font Beckman:size=10}W E A T H E R${font}
${offset 20}${voffset 3}${color}${font Beckman:bold:size=15}${execi 600 cat ~/.cache/weather.json | jq -r '.weather[0].main' | sed 's/.\{1\}/& /g;s/ $//'} / ${execi 600 cat ~/.cache/weather.json | jq '.main.temp' | awk '{print int($1+0.5)}' | sed 's/.\{1\}/& /g;s/ $//'} ${font Roboto:bold:size=15}°${font}
${offset 20}${voffset 6}${color}${font Beckman:size=10}T I M E  I S${font}
${offset 20}${voffset 3}${color}${font Beckman:bold:size=15}${exec LC_TIME=en_GB.UTF-8 date +%I:%M%P | sed 's/.\{1\}/& /g;s/ $//'}${font}
${offset 20}${voffset 19}${color}${font Beckman:size=10}C A L E N D A R${font}
${offset 20}${voffset 3}${color}${font Beckman:bold:size=15}${exec LC_TIME=en_GB.UTF-8 date +%B | sed 's/.\{1\}/& /g;s/ $//'} ${exec date +%d | sed 's/.\{1\}/& /g;s/ $//'} , ${exec date +%Y | sed 's/.\{1\}/& /g;s/ $//'}${font}
${offset 20}${voffset 19}${color}${font Beckman:size=10}T O D A Y ' S${font}
${offset 20}${voffset 3}${color}${font Beckman:bold:size=15}${exec LC_TIME=en_GB.UTF-8 date +%A | sed 's/.\{1\}/& /g;s/ $//'}${font}
]]
