

# portage/make.conf

PORTDIR="/var/db/repos/gentoo"
#PORTDIR_OVERLAY="/usr/local/portage"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
PORTAGE_TPMDIR="/tmp"

CCACHE_DIR="/var/cache/ccache"

COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

MAKEOPTS="-j14"

ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="~amd64"

EMERGE_DEFAULT_OPTS="--with-bdeps=y --ask --verbose=y --load-average --keep-going --deep"
AUTO_CLEAN="yes"

FEATURES="parallel-fetch ccache -test"
LC_MESSAGES=C.utf8

FETCHCOMMAND="/usr/bin/aria2c -d \${DISTDIR} -o \${FILE} --allow-overwrite=true --max-tries=5 --max-file-not-found=2 --max-concurrent-downloads=5 --connect-timeout=5 --timeout=5 --split=5 --min-split-size=2M --lowest-speed-limit=20K --max-connection-per-server=9 --uri-selector=feedback \${URI}"
RESUMECOMMAND="${FETCHCOMMAND}"

CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 ssse3 vpclmulqdq"
MICROCODE_SIGNATURES="-S"

GRUB_PLATFORMS="efi-64"

VIDEO_CARDS="intel i915 iris nvidia"
ALSA_CARDS="hda-intel"
INPUT_DEVICES="libinput synaptics"

L10N="en-GB ja-JP en ja"
LINGUAS="en-GB ja-JP en ja"

SSV_OPTS="elogind -bindist -mdev -systemd -consolekit -plymouth -grub -oss -gpm"
GRA_OPTS="X -wayland vulkan nvidia -nouveau layers gallium"
NET_OPTS="network nftables -iptables wifi connection-sharing http2 ppp networkmanager -dnsmasq -dhcpcd -netifrc"
AUD_OPTS="alsa jack pulseaudio"
SFW_OPTS="-icu udev client git blkid efi hwdb acpi sudo cjk fcitx5 -fcitx4 ccache dbus policykit udisks aria2 minizip smack emoji -gnome -gnome-keyring -gnome-shell -nautilus -kde -emacs"
OTH_OPTS="-docs -debug -test"
USE="${SSV_OPTS} ${GRA_OPTS} ${NET_OPTS} ${AUD_OPTS} ${SFW_OPTS} ${OTH_OPTS}"
