conky.config = {
--==============================================================================

--  Created : 2023/Feb/16
--  This theme is for conky version 1.10.8 or newer
-- 
--  MINTAKA ( Weather Celcius Version )
--  ( A part of Orion Conky themes pack )
--
--  author  : Closebox73
--  license : Distributed under the terms of GPLv3
--  notes   : Created on 1366x768 Monitor

--==============================================================================

-- Size and Position settings --
  alignment = 'middle_middle',
  gap_x = 0,
  gap_y = 0,
  maximum_width = 500,
  minimum_height = 310,
  minimum_width = 300,
  
-- Text settings --
  use_xft = true,
  override_utf8_locale = true,
  font='UzuraFont Nerd Font:size=1',
 
-- Color Settings --
  default_color = '#f8f8a8',
  default_outline_color = 'white',
  default_shade_color = 'white',
  
-- Window Settings --
  background = false,
  border_width = 1,
  draw_borders = false,
  draw_graph_borders = true,
  draw_outline = false,
  draw_shades = false,
  own_window = true,
  own_window_colour = '000000',
  own_window_class = 'Conky',
  own_window_argb_visual = false,
  own_window_type = 'override',
  own_window_transparent = true,
  own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
  stippled_borders = 0,
  
-- Others --
  cpu_avg_samples = 2,
  net_avg_samples = 2,
  double_buffer = true,
  out_to_console = false,
  out_to_stderr = false,
  extra_newline = false,
  update_interval = 1,
  uppercase = false,
  use_spacer = 'none',
  show_graph_scale = true,
  show_graph_range = true,
}

conky.text = [[
${execi 300 ~/.config/conky/Mintaka/scripts/weather-v2.0.sh}\
# ${image ~/.config/conky/Mintaka/res/box.png -p 28,0}\
# ${image ~/.config/conky/Mintaka/res/line.png -s 170x3 -p 7,215}\
${alignc}${voffset 36}${color}${font UzuraFont Nerd Font:size=10}${echo '\n'}${font}
${alignc}${voffset 20}${color}${font UzuraFont Nerd Font:size=20}${execi 100 cat ~/.cache/weather.json | jq '.main.temp' | awk '{print int($1+0.5)}'} °C - ${execi 100 cat ~/.cache/weather.json | jq -r '.weather[0].main'}${font}
${alignc}${voffset 36}${color}${font UzuraFont Nerd Font:size=20}${execi 60 LC_TIME=en_GB.UTF-8 date +"%b"} - ${execi 60 LC_TIME=en_GB.UTF-8 date +"%d"}${font}
${alignc}${voffset 14}${color}${font UzuraFont Nerd Font:size=45}${exec LC_TIME=en_GB.UTF-8 date +"%H:%M"}${font}
# ${alignc}${voffset 20}${color}${font Bebas Neue:size=45}${exec LC_TIME=en_GB.UTF-8 date +"%M" | sed 's/.\{1\}/&  /g;s/  $//'}${font}
${alignc}${voffset 20}${color}${font UzuraFont Nerd Font:size=45}${exec echo ' '}${font}
${alignc}${voffset 36}${color}${font UzuraFont Nerd Font:size=20}${echo '\n'}${font}
]]
