-- keymaps/dap.lua
--
local dap, k = require("dap"), vim.keymap
k.set("n", "<leader>sl", function()
  dap.continue()
end)
k.set("n", "<leader>sh", function()
  dap.step_over()
end)
k.set("n", "<leader>sj", function()
  dap.step_into()
end)
k.set("n", "<leader>sk", function()
  dap.step_out()
end)
k.set("n", "<leader>ss", function()
  dap.toggle_breakpoint()
end)
k.set("n", "<Leader>sS", function()
  dap.set_breakpoint(vim.fn.input("Condition: "), vim.fn.input("Hit condition: "), vim.fn.input("Log message: "))
end)
k.set("n", "<Leader>se", function()
  dap.set_exception_breakpoints()
end)
k.set("n", "<leader>sc", function()
  dap.clear_breakpoints()
end)
k.set("n", "<Leader>sq", function()
  dap.close()
end)
k.set("n", "<Leader>sQ", function()
  dap.terminate()
end)
k.set("n", "<leader>si", '<cmd>lua require("dapui").toggle()<cr>', { silent = true })
