#
#
# (|_|)
#
#
#
unsetopt BEEP
bindkey -v

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000

macchina

[[ -r ~/library/zsh-snap/znap/znap.zsh ]] ||
	git clone --depth 1 -- \
		https://github.com/marlonrichert/zsh-snap.git ~/library/zsh-snap/znap
source ~/library/zsh-snap/znap/znap.zsh 

alias nvrun="__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia"
alias vi="nvim"
alias svi="sudo nvim"
alias rr="ranger"
alias srr="sudo ranger"
alias em="sudo emerge"
alias es="sudo eselect"
alias s="sudo"
alias e="exit"
alias mk="sudo mount /dev/nvme0n1p1 /efi && sudo make modules_prepare && sudo make -j14 && sudo emerge -a @module-rebuild && sudo umount /dev/nvme0n1p1"
alias in="sudo mount /dev/nvme0n1p1 /efi && sudo make modules_install -j14 && sudo make install && sudo bootctl list && sudo umount /dev/nvme0n1p1"
alias toron="sudo systemctl start tor"
alias toroff="sudo systemctl stop tor"

PURE_PROMPT_SYMBOL="$"
PURE_PROMPT_VICMD_SYMBOL="&"

znap prompt sindresorhus/pure

ZSH_AUTOSUGGEST_STRATEGY=( history )
znap source zsh-users/zsh-autosuggestions

ZSH_HIGHLIGHT_HIGHLIGHTERS=( main brackets )
znap source zsh-users/zsh-syntax-highlighting
